import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/app/providers/theme-provider";
import { AuthProvider } from "./context/AuthContext";
import Navbar from "@/components/Navbar";
import { Toaster } from "sonner";
import { ProfileContextProvider } from "./context/ProfileContext";
import localFont from "next/font/local";
import { Recursive } from "next/font/google";
import ReactQueryProvider from "@/components/ReactQueryProvider";



const recursive = Recursive({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={recursive.className}>
        <AuthProvider>
          <ProfileContextProvider>
            <ReactQueryProvider>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
              >
                <Toaster
                  position="bottom-right"
                  theme="dark"
                  toastOptions={{
                    duration: 4000,
                    style: {
                      padding: "1rem",
                      fontSize: "0.95rem",
                      fontWeight: "500",
                    },
                  }}
                />
                <main className="flex flex-col min-h-[calc(100vh-3.5rem-1px)]">
                  <Navbar />
                  <div className="flex-1 flex flex-col h-full">{children}</div>
                </main>
              </ThemeProvider>
            </ReactQueryProvider>
          </ProfileContextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
